# Generated by Django 3.2.12 on 2022-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='babi', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
